version: "3.7"

services: 
  database:
    image: mysql:mysql-5.7
    enviroment:
      MYSQL_ROOTPASSWORD: P123456p
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: Clarusway_1
    networks:
      - clarusnet


  my-app:
    image: faith31434/bookstore:latest
    restart: always
    depends_on:
      - database
    ports: 
      - "80:80"
    networks:
      - clarusnet

networks:
  clarusnet:
    driver: bridge
    





